server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: flow-manager
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/files/**
        - id: subscription-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/subscriptions/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: apigateway
            client-secret: Dix7IuQTWIr5YNSPqH8sWZlFM4z1zv1o
            client-name: apigateway
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/apigateway

gateway:
  jwt:
    user-login-claim: preferred_username
  headers:
    user-login: X-User-Login
  filter:
    order: 100